---
- hosts : localhost
  tasks:
    - name : Pull Docker Image From Docker Hub
      shell : docker pull ashishkulkarni410/scientificcalculator:latest

    - name : Create Container
      shell : docker create -it --name scientificcalculator ashishkulkarni410/scientificcalculator:latest